spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  application: 
    name: forms-service
  datasource: 
    url: jdbc:mariadb://localhost:3309/omasagaforms?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true       
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    rest:
      base-path: /api
