spring:
  datasource: 
    url: jdbc:mariadb://localhost:3309/omasagafiles?useUnicode=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true        
  servlet:
    multipart: 
      max-file-size: 2048KB
      max-request-size: 2048KB
